[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
nixPkgs = ["nodejs_20"]
cmd = "echo 'Buildless setup - skipping build step'"

[start]
cmd = "node src/cli/index.js server --port $PORT --host 0.0.0.0"